version: "4.14"
services:
  mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
         - 8080:8080
  backend:
    build: ./backend
    ports:
      - "7000:7000"
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend




    



             