version: '3'
services: 
    backend: 
        image: node:16
        container_name : backend
        working_dir: /app
        command: npm start server
        ports : 
              - "7000:7000"
        volumes:  
        - "./backend/:/app"

        
    


