# version: "3"
# services:
  
#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     ports:
#      - 3000:3000
#     container_name: frontend
#     networks:
#      - livraison-marhaba-net
#     depends_on:
#      - backend
#     stdin_open: true
#     tty: true

#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     ports:
#      - 7000:7000
#     container_name: backend
#     networks:
#      - livraison-marhaba-net
#     depends_on:
#      - db

#   db:
#     image: mongo
#     ports:
#      - 27017:27017
#     container_name: db 
#     networks:
#      - livraison-marhaba-net

# networks:
#   marhaba-livraison-net:
#    driver: bridge
version: "4.14"
services:
  mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
         - 27017:27017
  backend:
    build: ./backend
    ports:
      - "7000:7000"
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend




    



             